// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SortDirection } from "./SortDirection";
import type { TurnItemsView } from "./TurnItemsView";

export type ThreadTurnsListParams = { threadId: string,
/**
 * Opaque cursor to pass to the next call to continue after the last turn.
 */
cursor?: string | null,
/**
 * Optional turn page size.
 */
limit?: number | null,
/**
 * Optional turn pagination direction; defaults to descending.
 */
sortDirection?: SortDirection | null,
/**
 * How much item detail to include for each returned turn; defaults to summary.
 */
itemsView?: TurnItemsView | null,
/**
 * Maximum serialized byte size for the response result. Values below 256 KiB
 * are rejected and values above 3 MiB are capped at 3 MiB.
 * Only summary and notLoaded item views support a byte budget.
 */
maxBytes?: number | null, };
